modLoader = "javafml"
loaderVersion = "[40,)"
license = "AGPL v3"
[[mods]]
modId = "bswk"
version = "1.0.0"
displayName = "BasaltWalker"
credits = ""
authors = "Hashtag233, Tapio"
description = '''
'''